### ISSUE TITLE
可以只让他显示中文的吗？ 不要对照的英文

### ISSUE THREAD

**Issue by pgy866** [herenwei/orchardcorechinesedocument#1]
可以只让他显示中文的吗？ 不要对照的英文

**Comment by herenwei** [comment]
可以。但是中英文对照不更好。因为自动翻译有些翻译有问题呀。对照就好理解。用谷歌翻译自己翻译下所有md就行了。

**Comment by pgy866** [comment]
为啥不保留官方的格式呢？这个格式看着有点别扭，如果可以左边中文，右边英文的方式展示就更好了

你这个是咋做的？ 我也想弄个？  

我跟OC官方提过一个，就是把他们的说明文档 用OC cms作为一个站点来维护更新内容，多美好啊

**Comment by herenwei** [comment]
做左右对照，格式比较难控制，因为翻译中文 英文高度不一样。你知道官方的文档怎么做的吧？就是它加上谷歌翻译，仅此而已。懂代码就随便怎么折腾。你可以去做，做这个定期维护比较难。因为没有专注在上面。他们官方的文档本来就少。很多需要自己去理解。

**Comment by pgy866** [comment]
确实是  我准备 做成 像谷歌翻译的 界面一样 左边中文右边英文   

内容就用Orachard core来管理 

然后在做三种内容展示的前端WEB UI，一种左右像谷歌翻译，一种全中文，一种全英文。


但是我好像 并不知这个货的 展示的一些原理

不好折腾，基础的文档没有，都是些高档的文档
