### ISSUE TITLE
这个翻译是怎么生成的啊？

### ISSUE THREAD

**Issue by hyzx86** [herenwei/orchardcorechinesedocument#2]
这个翻译项目是怎么做到的啊？
求教~!

**Comment by herenwei** [comment]
- 文档
    首先清楚orchard的文档生成的原理，是怎么生成的
- 解析
    了解文档的结构，拆分文档结构，一般按照句或者段落拆分。比如句号、空行、特殊标签
- 翻译
    编写代码，调用谷歌翻译api，对拆分的话进行翻译，插入原始文档对应位置即可
- 文档
    再次更具orchard原理，重新生成文档即可

**Comment by herenwei** [comment]
> 这个翻译项目是怎么做到的啊？
> 求教~!

文档
首先清楚orchard的文档生成的原理，是怎么生成的
解析
了解文档的结构，拆分文档结构，一般按照句或者段落拆分。比如句号、空行、特殊标签
翻译
编写代码，调用谷歌翻译api，对拆分的话进行翻译，插入原始文档对应位置即可
文档
再次更具orchard原理，重新生成文档即可

**Comment by hyzx86** [comment]
额，实现起来倒是不难，就是需要花费不少心思去整理
那么这个工具,或者这套脚本方便分享下吗？

我手头有维护一个官方发行的中文仓库：
https://github.com/OrchardCoreCn/OrchardCore
https://docs.orchardcore.net/zh_CN/dev/

我手动机器翻译了一部分，但是发现如果官方文档已更新的话，对比更新会很麻烦，所以翻译了一部分之后就放弃维护了

如果我们可以将这个过程自动化，那么这个项目将会更有意义

**Comment by herenwei** [comment]
> 额，实现起来倒是不难，就是需要花费不少心思去整理
> 那么这个工具,或者这套脚本方便分享下吗？
> 
> 我手头有维护一个官方发行的中文仓库：
> https://github.com/OrchardCoreCn/OrchardCore
> https://docs.orchardcore.net/zh_CN/dev/
> 
> 我手动机器翻译了一部分，但是发现如果官方文档已更新的话，对比更新会很麻烦，所以翻译了一部分之后就放弃维护了
> 
> 如果我们可以将这个过程自动化，那么这个项目将会更有意义

链接：https://pan.baidu.com/s/1gfHifR5MTF-dy7zpnJhm5Q 
提取码：v4an

**Comment by hyzx86** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月17日(星期一) 中午1:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [herenwei/orchardcorechinesedocument] 这个翻译是怎么生成的啊？ (#2)





  
额，实现起来倒是不难，就是需要花费不少心思去整理
 那么这个工具,或者这套脚本方便分享下吗？
 
我手头有维护一个官方发行的中文仓库：
 https://github.com/OrchardCoreCn/OrchardCore
 https://docs.orchardcore.net/zh_CN/dev/
 
我手动机器翻译了一部分，但是发现如果官方文档已更新的话，对比更新会很麻烦，所以翻译了一部分之后就放弃维护了
 
如果我们可以将这个过程自动化，那么这个项目将会更有意义
  
链接：https://pan.baidu.com/s/1gfHifR5MTF-dy7zpnJhm5Q
 提取码：v4an
 
&mdash;
